spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database
    driverClassName: com.mysql.cj.jdbc.Driver
    username: your_username
    password: your_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update